"""
This script prepares a dataset generated by PolNet to serve as input data to training nn-UNet for segmentation
considering that all input features are spheres
    Input:
        - A directory with the output of a PolNet dataset (see script data_gen/all_features.py)
        - Labels dictionary to match each structural with its label, labels not included in this dictionary are
          considered background
        - The radius of the sphere modeling the features
    Ouput:
        - A new directory with the structure required by nn-UNet for training a model for semantic segmentation
"""
__author__ = 'Antonio Martinez-Sanchez'

import os
import shutil
import nrrd
import json
import time
import torch

import numpy as np
import scipy as sp
import pandas as pd
import pandas

from glob import glob
from polnet import lio
from polnet.utils import *

ROOT_DIR = '/home/aguilar/Projects'
in_csv = ROOT_DIR + '/polnet/data/data_generated/300_tomos/tomos_motif_list.csv'
out_dir = ROOT_DIR + '/nnunet/nnUNet_raw'
dataset_id = '001'
dataset_suffix = 'pretrainingpolnet'
# fg_labels = {'membrane': (1, 2, 3), 'microtuble': (4,), 'actin': (5,), 'ribo': (6, 11, 12),
#              'cprots': tuple(np.arange(7, 11).tolist() + np.arange(13, 26).tolist()),  'mb_prot': tuple(range(26, 35))}
fg_labels = {
    "apo-ferritin": (1,),
    "beta-galactosidase": (2,),
    "ribosome": (3,),
    "thyroglobulin": (4,),
    "virus-like-particle": (5,),
}
fg_radii = {
    "apo-ferritin": 50,
    "beta-galactosidase": 80,
    "ribosome": 110,
    "thyroglobulin": 100,
    "virus-like-particle": 130,
} # in A
v_size_decimal = 3 # number of decimal to cut the voxel size precision
VOI_OFFS =  ((4,311), (4,311), (4,88)) # None (default)

# Parsing tomograms filenames from the CSV file
df = pandas.read_csv(in_csv, delimiter='\t')
tomos = set(df['Tomo3D'].tolist())
segs = dict()
for tomo in tomos:
    tomo_path, tomo_fname = os.path.split(tomo)
    segs[tomo] = tomo_path + '/tomo_lbls_' + tomo_fname.split('_')[2] + '.mrc'
assert len(tomos) == len(segs.keys())

# Create the dataset in nn-UNet format
out_dataset = out_dir + '/Dataset' + dataset_id + '_' + dataset_suffix
if os.path.exists(out_dataset):
    shutil.rmtree(out_dataset)
os.mkdir(out_dataset)
imgs_tr_dir, lbls_ts_dir = out_dataset + '/imagesTr', out_dataset + '/labelsTr'
os.mkdir(imgs_tr_dir)
os.mkdir(lbls_ts_dir)
out_labels = {'background': 0}
for tomo_id, tomo_in in enumerate(tomos):
    print('Processing tomogram:', tomo_in)
    tomo_df = df[df['Tomo3D'] == tomo_in]
    tomo = lio.load_mrc(tomo_in)

    tomo_gpu = torch.tensor(tomo, device="cuda")
    z, y, x = tomo_gpu.shape
    tomo = tomo_gpu.view(z // 2, 2, y // 2, 2, x // 2, 2).mean(dim=(1, 3, 5)).cpu().numpy()
    # seg_post = np.zeros(shape=tomo.shape, dtype=np.uint8)
    print(f"Tomogram shape = {tomo.shape}")
    seg_post = np.zeros(shape=(315,315,92), dtype=np.uint8)

    # Falta hacer algunas pruebas con los ejes

    # for filter_id, filter_name in enumerate(sorted(glob(f"{ROOT_DIR}/polnet/tsv/tomo*"))):
        
    #     target_spectrum = pd.read_csv(filter_name, sep="\t")["intensity"].values
    #     filtered_tomo = match_spectrum(tomo, target_spectrum, False, 0)

    v_sizes = lio.read_mrc_v_size(tomo_in)
    v_sizes = (round(float(v_sizes[0]), v_size_decimal), round(float(v_sizes[1]), v_size_decimal),
               round(float(v_sizes[2]), v_size_decimal))
    #     if (v_sizes[0] != v_sizes[1]) or (v_sizes[0] != v_sizes[2]):
    #         print('\t-WARNING: this tomograms cannot pre processes due to its anisotropic voxel size ', v_sizes)
    #         continue
    v_size_i = 1. / v_sizes[0]
    nrrd.write(imgs_tr_dir + '/tomo_' + str(tomo_id).zfill(3) + '_0000.nrrd', tomo)

    for i, key in enumerate(fg_labels.keys()):
        print('\tProcessing label:', key)
        hold_lbl = i + 1
        feat_df = tomo_df[(tomo_df['Label'].isin(fg_labels[key])) & (~tomo_df["Code"].isin(["ellipse"]))]
        
        tomo_centers = np.ones(shape=(315,315,92), dtype=bool)
        
        x_coords, y_coords, z_coords = feat_df['X'].to_numpy(), feat_df['Y'].to_numpy(), feat_df['Z'].to_numpy()
        coords = (np.round(x_coords * v_size_i /2).astype(int), np.round(y_coords * v_size_i/2).astype(int),
                  np.round(z_coords * v_size_i/2).astype(int))
        np.put(tomo_centers, np.ravel_multi_index(coords, dims=tomo_centers.shape), False, mode='clip')
        tomo_dsts = sp.ndimage.distance_transform_edt(tomo_centers).astype(np.float32)
        seg_post[tomo_dsts <= (fg_radii[key] * v_size_i/2)] = hold_lbl
        out_labels[key] = hold_lbl
        out_labels[key] = hold_lbl
    
    if VOI_OFFS is not None:
        off_mask = np.zeros(shape=seg_post.shape, dtype=seg_post.dtype)
        off_mask[VOI_OFFS[0][0]:VOI_OFFS[0][1], VOI_OFFS[1][0]:VOI_OFFS[1][1], VOI_OFFS[2][0]:VOI_OFFS[2][1]] = 1
        seg_post *= off_mask
    nrrd.write(lbls_ts_dir + '/tomo_' + str(tomo_id).zfill(3) + '.nrrd', seg_post)

# Json configuration file
dict_json = {
    'channel_names': {'0': 'zscore'},
    'labels': out_labels,
    'numTraining': len(tomos),
    'file_ending': '.nrrd'
}
with open(out_dataset + '/dataset.json', 'w') as outfile:
    outfile.write(json.dumps(dict_json, indent=4))

print('Successfully terminated. (' + time.strftime("%c") + ')')
